# Generated by Django 4.0.5 on 2022-06-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('currency_denominator', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=5, default=0.0, max_digits=12, verbose_name='Exchange Rate')),
                ('observation_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Exchange Rate History',
                'verbose_name_plural': 'Exchange Rate History',
                'ordering': ['currency', 'observation_date'],
            },
        ),
    ]
