# Generated by Django 4.0.5 on 2022-06-19 09:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('transaction_file', models.FileField(upload_to='transactions/uploads/', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
            ],
            options={
                'verbose_name': 'Transaction File Upload',
                'verbose_name_plural': 'Transaction File Uploads',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Transaction Type',
                'verbose_name_plural': 'Transaction Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateField(blank=True, help_text='Transaction date is in the following format e.g.: yyyy-mm-dd.', null=True, verbose_name='Transaction Date')),
                ('net', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Net')),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='VAT')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactiontype', verbose_name='Transaction Type')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['date', 'transaction_type', 'net'],
            },
        ),
    ]
